api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    enable_nelmio_api_doc: true
    formats:
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']
    collection:
        # The default order of results.
        order: 'ASC'
        # The name of the query parameter to order results.
        order_parameter_name: 'order'
        pagination:
            # To enable or disable pagination for all resource collections by default.
            enabled: true
            # To allow the client to enable or disable the pagination.
            client_enabled: false
            # To allow the client to set the number of items per page.
            client_items_per_page: false
            # The default number of items per page.
            items_per_page: 30
            # The maximum number of items per page.
            maximum_items_per_page: 30
            # The default name of the parameter handling the page number.
            page_parameter_name: 'page'
            # The name of the query parameter to enable or disable pagination.
            enabled_parameter_name: 'pagination'
            # The name of the query parameter to set the number of items per page.
            items_per_page_parameter_name: 'itemsPerPage'